- R/utils_helpers.R
> reorder species

- R/fct_species.R
- R/mod_a_fourth.R
- inst/translation.csv
> Conservation Status is now shown next to the map

- R/mod_a_fourth.R
> Correct issue with cache in renderTmap

- inst/app/www/custom.css
Note because of reformatting :
Implemented on the last two entries of the CSS files
Close #49
> Hiding pop ups in CSS

- R/app_ui.R
- R/fct_ui.R
- R/mod_c_second.R
- R/mod_d_third.R
- inst/app/www/custom.css
- inst/app/www/footer.html
> Footer height and the language select changes

- R/mod_c_second.R
- R/mod_d_third.R
> no sep in numbers

- R/mod_d_third.R
> Date unique sur l'onglet 4

- R/mod_c_second.R
- R/mod_c_second_fct_query_and_plot.R
- data-raw/bb-page1-catch-bycatch.Rmd
- data-raw/bd-page3-climate-change.Rmd
- dev/02_dev.R
- inst/app/www/custom.css
- inst/app/www/handlers.js
- inst/app/www/template.html
- renv.lock
> fix interactivity issues

- README.Rmd
- README.md
- app.R
- dev/02_dev.R
- dev/run_dev.R
Update instructions for local dev with Mongo
> dev instructions for mongo

- R/app_ui.R
- R/utils_helpers.R
- dev/translation.Rmd
- inst/translation.csv
- inst/translation_help.csv
- inst/translation_iucn.csv
> avec es et pt

- dev/translation.Rmd
- inst/translation.csv
- inst/translation_help.csv
Update after new translations in Google Sheet
> Translation with es & pt

- R/mod_c_third.R
- R/mod_c_third_fct_query_and_plot.R
- tests/testthat/test-mod_c_third_fct.R
> Make catchment selection explicit in tab 3

- .github/workflows/docker-build.yaml
- .github/workflows/docker-renv-coverage.yaml
- .github/workflows/docker-renv-pkgdown.yaml
- .github/workflows/docker-renv.yaml
- Dockerfile
- README.Rmd
- README.md
- renv.lock
Why?
Fails with new R version in env.lock
What?
Avoid renv warnings to stop building the container
> Update Dockerfile for R4.2

- NEWS.md
- R/app_ui.R
- data-raw/aa-a-exploration_data.Rmd
- inst/app/www/footer.html
Why?
- information required for debugging
What?
- Update footer with app and dbversion
issue # 112
> Add dbversion and app version in footer

- R/app_ui.R
- R/globals.R
- renv.lock
Why?
- Each time the db is updated, a new version appear in the version table
What?
- Extract the last version to add in the UI
issue #112
> Account for multiple dbversions

- DESCRIPTION
- README.Rmd
- README.md
- renv.lock
> Traduction pl

- renv.lock
- renv/settings.json
> CI: update Renv.lock

- dev/config_attachment.yaml
- renv/settings.json
> chore: setting files

- .Rprofile
- man/tm_draw.Rd
> Simulation run

- .github/workflows/docker-build.yaml
> CI: CI during pull request

- app.R
run_app(), used in production, is now consistent with run_dev() used to run the app in dev
- [x ] Est-ce que le check du package passe en local ?
- [x ] Est-ce que le CI passe ?
> fix: run_app() consistent with run_dev()

- DESCRIPTION
- NEWS.md
- renv.lock
- [ x] Est-ce que le check du package passe en local ?
> CI nex version of package
